LOAD DATA LOCAL INFILE 'Items.csv' INTO TABLE Items
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Sellers.csv' INTO TABLE Sellers
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Bidders.csv' INTO TABLE Bidders
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Bids.csv' INTO TABLE Bids
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'Categories.csv' INTO TABLE Categories
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';
